blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [

    path('', views.PostIndex.as_view(), name='blog_index'),
    path('categoria/<str:categoria>', views.PostCategoria.as_view(), name='post_categoria'),
    path('busca/', views.PostBusca.as_view(), name='post_busca'),
    path('novo/', views.PostCreate.as_view(), name='novo-post'),
    path('update/<int:pk>', views.PostUpdateView.as_view(), name='update-post'),
    path('delete/<int:pk>', views.PostDeleteView.as_view(), name='delete-post'),
    path('post/<int:pk>', views.PostDetalhes.as_view(), name='post_detalhes'),
    

]

raiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [


    path('principal', include('principal.urls')),
    path('', include('blog.urls')),

    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image
from django.conf import settings
import os

# model de categoria
class Categoria(models.Model):

    nome_categoria = models.CharField(max_length=50)
    
    #metodo que retorma um nome para a classe
    def __str__(self):
        return self.nome_categoria  

# model de post
class Post(models.Model):

    titulo_post = models.CharField(max_length=255, verbose_name='Titulo')
    autor_post = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Autor')
    data_post = models.DateTimeField(default=timezone.now, verbose_name='Data da Publicação')
    conteudo_post = models.TextField(verbose_name='Conteúdo')
    excerto_post = models.TextField(verbose_name='Sumário')
    categoria_post = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING, blank=False, null=False, verbose_name='Categoria')
    imagem_post = models.ImageField(upload_to='post_img/%Y/%m/%d', blank=False, null=False, verbose_name='Imagem')
    publicado_post = models.BooleanField(default=False, verbose_name='Publicado')

    #metodo que retorma um nome para a classe
    def __str__(self):
        return self.titulo_post   


# model de comentario
class Comentario(models.Model):

    nome_comentario = models.CharField(max_length=150, verbose_name='Nome')
    email_comentario = models.EmailField(verbose_name='E-mail')
    comentario = models.TextField(verbose_name='Comentário')
    post_comentario = models.ForeignKey(Post, on_delete=models.CASCADE)
    usuario_comentario = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=True, null=True)
    data_comentario = models.DateTimeField(default=timezone.now) #lembrar de declarar timezone lá em cima
    publicado_comentario = models.BooleanField(default=False) 

    #metodo que retorma um nome para a classe    
    def __str__(self):
        return self.nome_comentario    

templates/parciais/_footer.html
{% load static %}


	<!-- Social links. @TODO: replace by link/instructions in template -->
	<section id="social">
		<div class="container">
			<div class="wrapper clearfix">
				<!-- AddThis Button BEGIN -->
				<div class="addthis_toolbox addthis_default_style">
				<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
				<a class="addthis_button_tweet"></a>
				<a class="addthis_button_linkedin_counter"></a>
				<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
				</div>
				<!-- AddThis Button END -->
			</div>
		</div>
	</section>
	<!-- /social links -->


	<footer id="footer" class="top-space">

		<div class="footer-area footer-bg">
			<div class="container">
				<div class="row">
					
					<div class="col-md-3 widget">
						
						<div class="widget-body">
							<br>
							<img src="{% static 'img/principal/jack.jpg' %}" height="230" width="350"alt=""></a>
							
						</div>
						<br>
					</div>

					<div class="col-md-3 widget">
					
						<div class="widget-body">
							
						</div>
					</div>

					<div class="col-md-6 widget">
						
						<div class="widget-body">
							<br>
							<a href="{% url 'blog_index' %}"><img src="{% static 'img/logo/logo1.png' %}" alt=""></a>
							
						</div>
						<br>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

		<div class="footer-bottom">
			<div class="row d-flex align-items-center">
				<div class="col-lg-12">
					<div class="footer-copy-right text-center">
						<p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | <i class="fas fa-skull-crossbones"></i>  Yuri M Menezes</p> 
										
						{% if user.is_authenticated %}
														
						<a href="#">Usuario Logado: {{user.username}}</a></li>          
				  
						{% endif %}
					</div>
				</div>
			</div>
		</div>

	</footer>	
		



<!-- Scroll Up -->
<div id="back-top" >
    <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
</div>

    <!-- JS here --> 

    <!-- JS da cabeira laranjada do footer --> 
	
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    

    <script type="text/javascript" src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>

    <!-- Jquery, Popper, Bootstrap -->
 
    <script type="text/javascript" src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Jquery Mobile Menu -->
    
    <script type="text/javascript" src="{% static 'js/jquery.slicknav.min.js' %}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    
    <script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slick.min.js' %}"></script>
    <!-- One Page, Animated-HeadLin -->
    
    <script type="text/javascript" src="{% static 'js/wow.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/animated.headline.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.magnific-popup.js' %}"></script>

    <!-- Nice-select, sticky -->

    <script type="text/javascript" src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.sticky.js' %}"></script>
    
    <!-- contact js -->
   
    <script type="text/javascript" src="{% static 'js/contact.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.form.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.validate.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/mail-script.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
    
    <!-- Jquery Plugins, main Jquery -->	
    
    <script type="text/javascript" src="{% static 'js/plugins.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

templates/parciais/_head.html
{% load static %}

   
<head>
 <meta charset="utf-8">
 <meta http-equiv="x-ua-compatible" content="ie=edge">
 <title>Projeto Prometheus</title>
 <meta name="description" content="">
 <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="manifest" href="site.webmanifest">
 
 
 <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/logo/favicon.ico' %}">


 <!-- Validação recapcha -->
 <script src="https://www.google.com/recaptcha/api.js" async defer></script>
			
 <!-- CSS here -->
 
 <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">


 
 
 <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">

 <link rel="stylesheet" type="text/css" href="{% static 'css/slicknav.css' %}">
 
 <link rel="stylesheet" type="text/css" href="{% static 'css/flaticon.css' %}">
 
 <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">
 
 <link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
 
 <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">
 
 <link rel="stylesheet" type="text/css" href="{% static 'css/themify-icons.css' %}">
 
 <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
 
 <link rel="stylesheet" type="text/css" href="{% static 'css/nice-select.css' %}">

 <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>

templates/parciais/_intro.html
    <!-- Header -->

	<header id="head">
		<div class="container">
			<div class="row">
				<h1 class="lead">Escolha, Apenas Uma vez!!!</h1>
				<p class="tagline">########################<a href="#">|||||||</a></p>
				<p><a class="btn btn-default btn-lg" role="button">???</a> <a class="btn btn-action btn-lg" role="button">???</a></p>
			</div>
		</div>
	</header>

	<!-- /Header -->


	<!-- Intro -->
	<div class="container text-center">
		<br> <br>
		<h2 class="thin">The best place to tell people why they are here</h2>
		<p class="text-muted">
			The difference between involvement and commitment is like an eggs-and-ham breakfast:<br> 
			the chicken was involved; the pig was committed.
		</p>
	</div>
	<!-- /Intro-->
		

templates/parciais/_lateral.html
{% load static %}
{% load humanize %}

<div class="col-lg-4">
    <div class="blog_right_sidebar">
        <aside class="single_sidebar_widget search_widget">
            <form action="{% url 'post_busca' %}">
                <div class="form-group">
                    <div class="input-group mb-3">
                        <input name="termo" value="{{ request.GET.termo }}" class="form-control mr-sm-2" type="search" placeholder="Pesquisar"
                            onfocus="this.placeholder = ''"
                            onblur="this.placeholder = 'Pesquisar'">
                       
                    </div>
                </div>
                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                    type="submit">Buscar</button>
            </form>
        </aside>

      
        <aside class="single_sidebar_widget post_category_widget">
            <h4 class="widget_title">Categorias</h4>
            <ul class="list cat-list">
                <li>
                    <a href="#" class="d-flex">
                        <p>Animes</p>
                        
                    </a>
                </li>
                <li>
                    <a href="#" class="d-flex">
                        <p>Tecnologia</p>
                       
                    </a>
                </li>

                <li>
                    <a href="#" class="d-flex">
                        <p>Tutoriais</p>
                        
                    </a>
                </li>

                <li>
                    <a href="#" class="d-flex">
                        <p>Games</p>
                        
                    </a>
                </li>

                <li>
                    <a href="#" class="d-flex">
                        <p>Filmes e Séries</p>
                       
                    </a>
                </li>

            </ul>
        </aside>

        <aside class="single_sidebar_widget popular_post_widget">
                <h3 class="widget_title">Últimas Postagens</h3>
            {% for post in posts %}<!-- a varialvel post faz referencia ao que deve ser usado no html e o pots ta sendo trazido da viewr com a pesquisa-->
                <div class="card">
                    {% if post.imagem_post %}   
                        <a href="{% url 'post_detalhes' post.id %}">
                            <img class="card-img-top"
                                    src="{{ post.imagem_post.url }}"
                                    alt="{{ post.titulo_post }}">
                        </a>
                    {% endif %}      
    
                    <div class="card-body">
                    <h5 class="card-title">
                        <a href="{% url 'post_detalhes' post.id %}">
                            {{ post.titulo_post }}
                        </a>
                    </h5>
                    <p class="card-text">{{ post.exerto_post }}</p>
                    <p class="card-text">
    
                        <small class="text-muted">
    
                            {{ post.data_post|naturalday|title }}<!--usa o metodo humanize referenciado no instal apps para formatar a data-->
                            |
                            {{ post.numero_comentarios }} Comentário(s)
                            <!-- esse jeito abaixo apenas conta quantos comentarios tem o post o no acima separa os comentarios publicados ou não-->
                            <!--{{ post.comentario_set.count }} Comentário(s)<!-- conta e mostra quantos comentarios existem pra determinado post, obs:comentario é um foreidkey -->
                            |
                            {{ post.categoria_post }}<!--lista e associa a categoria cadastrada pra determinadado post, obs: categoria é um foreidkey -->
    
                        </small>
    
                    </p>
    
                    </div>
                </div>

            {% endfor %}    
         </aside>    
    
            
        <!--/FOR LOOP-->
       
    </div>
</div>

templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
{% load static %}



    <!--? Preloader Start -->
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <img src="{% static 'img/logo/loder.jpg' %}" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Preloader Start -->
<header>
    <!-- Header Start -->
    <div class="header-area">
        <div class="main-header ">
            <div class="header-top d-none d-lg-block">
                <div class="container">
                    <div class="col-xl-12">
                        <div class="row d-flex justify-content-between align-items-center">
                            <div class="header-info-left">
                                <ul>     
                                    <li>Phone: +99 (0) 101 0000 888</li>
                                    <li>Email: noreply@yourdomain.com</li>
                                </ul>
                            </div>
                            <div class="header-info-right">
                                <ul class="header-social">    
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                    <li> <a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="header-bottom  header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo">
                                <a href="#"><img src="{% static 'img/logo/logo1.png' %}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10">
                            <div class="menu-wrapper  d-flex align-items-center justify-content-end">
                                <!-- Main-menu -->
                                <div class="main-menu d-none d-lg-block">
                                    <nav> 
                                        <ul id="navigation">                                                                                          
                                            <li><a href="#">Home</a></li>
                                            <li><a href="#">About</a></li>
                                            <li><a href="#">Services</a></li>
                                            <li><a href="#">Blog</a>
                                                <ul class="submenu">
                                                    <li><a href="#">Blog</a></li>
                                                    <li><a href="#">Blog Details</a></li>
                                                    <li><a href="#">Element</a></li>
                                                </ul>
                                            </li>
                                            <li><a href="#">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                                <!-- Header-btn -->
                                                 
                                {% if user.is_authenticated %}
                                                            
                                <li> 
                                    <li><a href="#">Usuario Logado: {{user.username}}</a></li>          
                                 
                                </li>
                                    
                                <a href="{% url 'logout' %}" class="sc-add-to-cart btn btn-primary">logout</a>
                                    
                                {% else %}
                                    
                                    
                                <a href="{% url 'login' %}" class="sc-add-to-cart btn btn-primary">Login</a>
                                
                                {% endif %}
                            </div>
                        </div> 
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>
    

templates/parciais/_pagination.html
{% load static %}

{% if is_paginated %}

    <div class="col-lg-8 mb-5 mb-lg-0">
                    
                                    
        <div class="blog_left_sidebar">
                                    
            <nav class="blog-pagination justify-content-center d-flex">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">&laquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                    </li>
                    {% endif %}
            
                    {% for num in page_obj.paginator.page_range %}
            
                    {% if page_obj.number == num %}
                    <li class="page-item active">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                    {% endif %}
            
                    {% endfor %}
            
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>

    </div>

{% endif %}